config/routes.rb
Rails.application.routes.draw do
  get 'categorias/index'

  get 'welcome/index'

  resources :gestions
  resources :subtipos
  resources :caracteristicadeco2s
  resources :caracteristicadeco1s
  resources :deco2s
  resources :deco1s
  resources :antenapuntos
  resources :caracteristicamodems
  resources :modems
  resources :caracteristicatelefonos
  resources :telefonos
  resources :descuentos
  resources :promocions
  resources :modopagos
  resources :tecnos
  resources :administrativas
  resources :ocpaquetes
  resources :internets
  resources :lineas
  resources :paquetes
  resources :tipos
  resources :zonals
  resources :campanas
  resources :origens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/antenapunto.rb
class Antenapunto < ApplicationRecord
end

app/models/campana.rb
class Campana < ApplicationRecord
end

app/models/deco1.rb
class Deco1 < ApplicationRecord
end

app/models/deco2.rb
class Deco2 < ApplicationRecord
end

app/models/descuento.rb
class Descuento < ApplicationRecord
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :origen
  belongs_to :campana
  belongs_to :zonal
  belongs_to :tipo
  belongs_to :subtipo
  belongs_to :paquete
  belongs_to :linea
  belongs_to :internet
  belongs_to :administrativa
  belongs_to :tecno
  belongs_to :modopago
  belongs_to :promocion
  belongs_to :descuento
  belongs_to :telefono
  belongs_to :caracteristicatelefono
  belongs_to :modem
  belongs_to :caracteristicamodem
  belongs_to :antenapunto
  belongs_to :deco1
  belongs_to :caracteristicadeco1
  belongs_to :deco2
  belongs_to :caracteristicadeco2
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/linea.rb
class Linea < ApplicationRecord
end

app/models/modem.rb
class Modem < ApplicationRecord
end

app/models/modopago.rb
class Modopago < ApplicationRecord
end

app/models/ocpaquete.rb
class Ocpaquete < ApplicationRecord
end

app/models/origen.rb
class Origen < ApplicationRecord
end

app/models/paquete.rb
class Paquete < ApplicationRecord
end

app/models/promocion.rb
class Promocion < ApplicationRecord
end

app/models/subtipo.rb
class Subtipo < ApplicationRecord
end

app/models/tecno.rb
class Tecno < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/zonal.rb
class Zonal < ApplicationRecord
end

app/controllers/internets_controller.rb
class InternetsController < ApplicationController
  before_action :set_internet, only: [:show, :edit, :update, :destroy]

  # GET /internets
  # GET /internets.json
  def index
    @internets = Internet.all
  end

  # GET /internets/1
  # GET /internets/1.json
  def show
  end

  # GET /internets/new
  def new
    @internet = Internet.new
  end

  # GET /internets/1/edit
  def edit
  end

  # POST /internets
  # POST /internets.json
  def create
    @internet = Internet.new(internet_params)

    respond_to do |format|
      if @internet.save
        format.html { redirect_to @internet, notice: 'Internet was successfully created.' }
        format.json { render :show, status: :created, location: @internet }
      else
        format.html { render :new }
        format.json { render json: @internet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internets/1
  # PATCH/PUT /internets/1.json
  def update
    respond_to do |format|
      if @internet.update(internet_params)
        format.html { redirect_to @internet, notice: 'Internet was successfully updated.' }
        format.json { render :show, status: :ok, location: @internet }
      else
        format.html { render :edit }
        format.json { render json: @internet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internets/1
  # DELETE /internets/1.json
  def destroy
    @internet.destroy
    respond_to do |format|
      format.html { redirect_to internets_url, notice: 'Internet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internet
      @internet = Internet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internet_params
      params.require(:internet).permit(:pack, :tipo_pago, :costo)
    end
end

app/helpers/deco1s_helper.rb
module Deco1sHelper
end

app/helpers/internets_helper.rb
module InternetsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/internets/_form.html.erb
<%= form_for(internet) do |f| %>
  <% if internet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internet.errors.count, "error") %> prohibited this internet from being saved:</h2>

      <ul>
      <% internet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pack %>
    <%= f.text_field :pack %>
  </div>

  <div class="field">
    <%= f.label :tipo_pago %>
    <%= f.text_field :tipo_pago %>
  </div>

  <div class="field">
    <%= f.label :costo %>
    <%= f.text_field :costo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/internets/edit.html.erb
<h1>Editing Internet</h1>

<%= render 'form', internet: @internet %>

<%= link_to 'Show', @internet %> |
<%= link_to 'Back', internets_path %>

app/views/internets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Internets</h1>

<table>
  <thead>
    <tr>
      <th>Pack</th>
      <th>Tipo pago</th>
      <th>Costo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @internets.each do |internet| %>
      <tr>
        <td><%= internet.pack %></td>
        <td><%= internet.tipo_pago %></td>
        <td><%= internet.costo %></td>
        <td><%= link_to 'Show', internet %></td>
        <td><%= link_to 'Edit', edit_internet_path(internet) %></td>
        <td><%= link_to 'Destroy', internet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Internet', new_internet_path %>

app/views/internets/new.html.erb
<h1>New Internet</h1>

<%= render 'form', internet: @internet %>

<%= link_to 'Back', internets_path %>

app/views/internets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pack:</strong>
  <%= @internet.pack %>
</p>

<p>
  <strong>Tipo pago:</strong>
  <%= @internet.tipo_pago %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @internet.costo %>
</p>

<%= link_to 'Edit', edit_internet_path(@internet) %> |
<%= link_to 'Back', internets_path %>