config/routes.rb
Rails.application.routes.draw do
  get 'categorias/index'

  get 'welcome/index'

  resources :gestions
  resources :subtipos
  resources :caracteristicadeco2s
  resources :caracteristicadeco1s
  resources :deco2s
  resources :deco1s
  resources :antenapuntos
  resources :caracteristicamodems
  resources :modems
  resources :caracteristicatelefonos
  resources :telefonos
  resources :descuentos
  resources :promocions
  resources :modopagos
  resources :tecnos
  resources :administrativas
  resources :ocpaquetes
  resources :internets
  resources :lineas
  resources :paquetes
  resources :tipos
  resources :zonals
  resources :campanas
  resources :origens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/antenapunto.rb
class Antenapunto < ApplicationRecord
end

app/models/campana.rb
class Campana < ApplicationRecord
end

app/models/deco1.rb
class Deco1 < ApplicationRecord
end

app/models/deco2.rb
class Deco2 < ApplicationRecord
end

app/models/descuento.rb
class Descuento < ApplicationRecord
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :origen
  belongs_to :campana
  belongs_to :zonal
  belongs_to :tipo
  belongs_to :subtipo
  belongs_to :paquete
  belongs_to :linea
  belongs_to :internet
  belongs_to :administrativa
  belongs_to :tecno
  belongs_to :modopago
  belongs_to :promocion
  belongs_to :descuento
  belongs_to :telefono
  belongs_to :caracteristicatelefono
  belongs_to :modem
  belongs_to :caracteristicamodem
  belongs_to :antenapunto
  belongs_to :deco1
  belongs_to :caracteristicadeco1
  belongs_to :deco2
  belongs_to :caracteristicadeco2
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/linea.rb
class Linea < ApplicationRecord
end

app/models/modem.rb
class Modem < ApplicationRecord
end

app/models/modopago.rb
class Modopago < ApplicationRecord
end

app/models/ocpaquete.rb
class Ocpaquete < ApplicationRecord
end

app/models/origen.rb
class Origen < ApplicationRecord
end

app/models/paquete.rb
class Paquete < ApplicationRecord
end

app/models/promocion.rb
class Promocion < ApplicationRecord
end

app/models/subtipo.rb
class Subtipo < ApplicationRecord
end

app/models/tecno.rb
class Tecno < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/zonal.rb
class Zonal < ApplicationRecord
end

app/controllers/promocions_controller.rb
class PromocionsController < ApplicationController
  before_action :set_promocion, only: [:show, :edit, :update, :destroy]

  # GET /promocions
  # GET /promocions.json
  def index
    @promocions = Promocion.all
  end

  # GET /promocions/1
  # GET /promocions/1.json
  def show
  end

  # GET /promocions/new
  def new
    @promocion = Promocion.new
  end

  # GET /promocions/1/edit
  def edit
  end

  # POST /promocions
  # POST /promocions.json
  def create
    @promocion = Promocion.new(promocion_params)

    respond_to do |format|
      if @promocion.save
        format.html { redirect_to @promocion, notice: 'Promocion was successfully created.' }
        format.json { render :show, status: :created, location: @promocion }
      else
        format.html { render :new }
        format.json { render json: @promocion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocions/1
  # PATCH/PUT /promocions/1.json
  def update
    respond_to do |format|
      if @promocion.update(promocion_params)
        format.html { redirect_to @promocion, notice: 'Promocion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocion }
      else
        format.html { render :edit }
        format.json { render json: @promocion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocions/1
  # DELETE /promocions/1.json
  def destroy
    @promocion.destroy
    respond_to do |format|
      format.html { redirect_to promocions_url, notice: 'Promocion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocion
      @promocion = Promocion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocion_params
      params.require(:promocion).permit(:costo, :tiempo)
    end
end

app/helpers/deco1s_helper.rb
module Deco1sHelper
end

app/helpers/promocions_helper.rb
module PromocionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/promocions/_form.html.erb
<%= form_for(promocion) do |f| %>
  <% if promocion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocion.errors.count, "error") %> prohibited this promocion from being saved:</h2>

      <ul>
      <% promocion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :costo %>
    <%= f.text_field :costo %>
  </div>

  <div class="field">
    <%= f.label :tiempo %>
    <%= f.text_field :tiempo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promocions/edit.html.erb
<h1>Editing Promocion</h1>

<%= render 'form', promocion: @promocion %>

<%= link_to 'Show', @promocion %> |
<%= link_to 'Back', promocions_path %>

app/views/promocions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promocions</h1>

<table>
  <thead>
    <tr>
      <th>Costo</th>
      <th>Tiempo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocions.each do |promocion| %>
      <tr>
        <td><%= promocion.costo %></td>
        <td><%= promocion.tiempo %></td>
        <td><%= link_to 'Show', promocion %></td>
        <td><%= link_to 'Edit', edit_promocion_path(promocion) %></td>
        <td><%= link_to 'Destroy', promocion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocion', new_promocion_path %>

app/views/promocions/new.html.erb
<h1>New Promocion</h1>

<%= render 'form', promocion: @promocion %>

<%= link_to 'Back', promocions_path %>

app/views/promocions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Costo:</strong>
  <%= @promocion.costo %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= @promocion.tiempo %>
</p>

<%= link_to 'Edit', edit_promocion_path(@promocion) %> |
<%= link_to 'Back', promocions_path %>