config/routes.rb
Rails.application.routes.draw do
  get 'categorias/index'

  get 'welcome/index'

  resources :gestions
  resources :subtipos
  resources :caracteristicadeco2s
  resources :caracteristicadeco1s
  resources :deco2s
  resources :deco1s
  resources :antenapuntos
  resources :caracteristicamodems
  resources :modems
  resources :caracteristicatelefonos
  resources :telefonos
  resources :descuentos
  resources :promocions
  resources :modopagos
  resources :tecnos
  resources :administrativas
  resources :ocpaquetes
  resources :internets
  resources :lineas
  resources :paquetes
  resources :tipos
  resources :zonals
  resources :campanas
  resources :origens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/antenapunto.rb
class Antenapunto < ApplicationRecord
end

app/models/campana.rb
class Campana < ApplicationRecord
end

app/models/deco1.rb
class Deco1 < ApplicationRecord
end

app/models/deco2.rb
class Deco2 < ApplicationRecord
end

app/models/descuento.rb
class Descuento < ApplicationRecord
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :origen
  belongs_to :campana
  belongs_to :zonal
  belongs_to :tipo
  belongs_to :subtipo
  belongs_to :paquete
  belongs_to :linea
  belongs_to :internet
  belongs_to :administrativa
  belongs_to :tecno
  belongs_to :modopago
  belongs_to :promocion
  belongs_to :descuento
  belongs_to :telefono
  belongs_to :caracteristicatelefono
  belongs_to :modem
  belongs_to :caracteristicamodem
  belongs_to :antenapunto
  belongs_to :deco1
  belongs_to :caracteristicadeco1
  belongs_to :deco2
  belongs_to :caracteristicadeco2
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/linea.rb
class Linea < ApplicationRecord
end

app/models/modem.rb
class Modem < ApplicationRecord
end

app/models/modopago.rb
class Modopago < ApplicationRecord
end

app/models/ocpaquete.rb
class Ocpaquete < ApplicationRecord
end

app/models/origen.rb
class Origen < ApplicationRecord
end

app/models/paquete.rb
class Paquete < ApplicationRecord
end

app/models/promocion.rb
class Promocion < ApplicationRecord
end

app/models/subtipo.rb
class Subtipo < ApplicationRecord
end

app/models/tecno.rb
class Tecno < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/zonal.rb
class Zonal < ApplicationRecord
end

app/controllers/origens_controller.rb
class OrigensController < ApplicationController
  before_action :set_origen, only: [:show, :edit, :update, :destroy]

  # GET /origens
  # GET /origens.json
  def index
    @origens = Origen.all
  end

  # GET /origens/1
  # GET /origens/1.json
  def show
  end

  # GET /origens/new
  def new
    @origen = Origen.new
  end

  # GET /origens/1/edit
  def edit
  end

  # POST /origens
  # POST /origens.json
  def create
    @origen = Origen.new(origen_params)

    respond_to do |format|
      if @origen.save
        format.html { redirect_to @origen, notice: 'Origen was successfully created.' }
        format.json { render :show, status: :created, location: @origen }
      else
        format.html { render :new }
        format.json { render json: @origen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /origens/1
  # PATCH/PUT /origens/1.json
  def update
    respond_to do |format|
      if @origen.update(origen_params)
        format.html { redirect_to @origen, notice: 'Origen was successfully updated.' }
        format.json { render :show, status: :ok, location: @origen }
      else
        format.html { render :edit }
        format.json { render json: @origen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /origens/1
  # DELETE /origens/1.json
  def destroy
    @origen.destroy
    respond_to do |format|
      format.html { redirect_to origens_url, notice: 'Origen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_origen
      @origen = Origen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def origen_params
      params.require(:origen).permit(:nombre_origen, :descripcion)
    end
end

app/helpers/deco1s_helper.rb
module Deco1sHelper
end

app/helpers/origens_helper.rb
module OrigensHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/origens/_form.html.erb
<%= form_for(origen) do |f| %>
  <% if origen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(origen.errors.count, "error") %> prohibited this origen from being saved:</h2>

      <ul>
      <% origen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_origen %>
    <%= f.text_field :nombre_origen %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/origens/edit.html.erb
<h1>Editing Origen</h1>

<%= render 'form', origen: @origen %>

<%= link_to 'Show', @origen %> |
<%= link_to 'Back', origens_path %>

app/views/origens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Origens</h1>

<table>
  <thead>
    <tr>
      <th>Nombre origen</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @origens.each do |origen| %>
      <tr>
        <td><%= origen.nombre_origen %></td>
        <td><%= origen.descripcion %></td>
        <td><%= link_to 'Show', origen %></td>
        <td><%= link_to 'Edit', edit_origen_path(origen) %></td>
        <td><%= link_to 'Destroy', origen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Origen', new_origen_path %>

app/views/origens/new.html.erb
<h1>New Origen</h1>

<%= render 'form', origen: @origen %>

<%= link_to 'Back', origens_path %>

app/views/origens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre origen:</strong>
  <%= @origen.nombre_origen %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @origen.descripcion %>
</p>

<%= link_to 'Edit', edit_origen_path(@origen) %> |
<%= link_to 'Back', origens_path %>