config/routes.rb
Rails.application.routes.draw do
  get 'categorias/index'

  get 'welcome/index'

  resources :gestions
  resources :subtipos
  resources :caracteristicadeco2s
  resources :caracteristicadeco1s
  resources :deco2s
  resources :deco1s
  resources :antenapuntos
  resources :caracteristicamodems
  resources :modems
  resources :caracteristicatelefonos
  resources :telefonos
  resources :descuentos
  resources :promocions
  resources :modopagos
  resources :tecnos
  resources :administrativas
  resources :ocpaquetes
  resources :internets
  resources :lineas
  resources :paquetes
  resources :tipos
  resources :zonals
  resources :campanas
  resources :origens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/antenapunto.rb
class Antenapunto < ApplicationRecord
end

app/models/campana.rb
class Campana < ApplicationRecord
end

app/models/deco1.rb
class Deco1 < ApplicationRecord
end

app/models/deco2.rb
class Deco2 < ApplicationRecord
end

app/models/descuento.rb
class Descuento < ApplicationRecord
end

app/models/gestion.rb
class Gestion < ApplicationRecord
  belongs_to :origen
  belongs_to :campana
  belongs_to :zonal
  belongs_to :tipo
  belongs_to :subtipo
  belongs_to :paquete
  belongs_to :linea
  belongs_to :internet
  belongs_to :administrativa
  belongs_to :tecno
  belongs_to :modopago
  belongs_to :promocion
  belongs_to :descuento
  belongs_to :telefono
  belongs_to :caracteristicatelefono
  belongs_to :modem
  belongs_to :caracteristicamodem
  belongs_to :antenapunto
  belongs_to :deco1
  belongs_to :caracteristicadeco1
  belongs_to :deco2
  belongs_to :caracteristicadeco2
end

app/models/internet.rb
class Internet < ApplicationRecord
end

app/models/linea.rb
class Linea < ApplicationRecord
end

app/models/modem.rb
class Modem < ApplicationRecord
end

app/models/modopago.rb
class Modopago < ApplicationRecord
end

app/models/ocpaquete.rb
class Ocpaquete < ApplicationRecord
end

app/models/origen.rb
class Origen < ApplicationRecord
end

app/models/paquete.rb
class Paquete < ApplicationRecord
end

app/models/promocion.rb
class Promocion < ApplicationRecord
end

app/models/subtipo.rb
class Subtipo < ApplicationRecord
end

app/models/tecno.rb
class Tecno < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/models/zonal.rb
class Zonal < ApplicationRecord
end

app/controllers/campanas_controller.rb
class CampanasController < ApplicationController
  before_action :set_campana, only: [:show, :edit, :update, :destroy]

  # GET /campanas
  # GET /campanas.json
  def index
    @campanas = Campana.all
  end

  # GET /campanas/1
  # GET /campanas/1.json
  def show
  end

  # GET /campanas/new
  def new
    @campana = Campana.new
  end

  # GET /campanas/1/edit
  def edit
  end

  # POST /campanas
  # POST /campanas.json
  def create
    @campana = Campana.new(campana_params)

    respond_to do |format|
      if @campana.save
        format.html { redirect_to @campana, notice: 'Campana was successfully created.' }
        format.json { render :show, status: :created, location: @campana }
      else
        format.html { render :new }
        format.json { render json: @campana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campanas/1
  # PATCH/PUT /campanas/1.json
  def update
    respond_to do |format|
      if @campana.update(campana_params)
        format.html { redirect_to @campana, notice: 'Campana was successfully updated.' }
        format.json { render :show, status: :ok, location: @campana }
      else
        format.html { render :edit }
        format.json { render json: @campana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campanas/1
  # DELETE /campanas/1.json
  def destroy
    @campana.destroy
    respond_to do |format|
      format.html { redirect_to campanas_url, notice: 'Campana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campana
      @campana = Campana.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campana_params
      params.require(:campana).permit(:nombre_camapana, :descripcion)
    end
end

app/helpers/campanas_helper.rb
module CampanasHelper
end

app/helpers/deco1s_helper.rb
module Deco1sHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/campanas/_form.html.erb
<%= form_for(campana) do |f| %>
  <% if campana.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campana.errors.count, "error") %> prohibited this campana from being saved:</h2>

      <ul>
      <% campana.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_camapana %>
    <%= f.text_field :nombre_camapana %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campanas/edit.html.erb
<h1>Editing Campana</h1>

<%= render 'form', campana: @campana %>

<%= link_to 'Show', @campana %> |
<%= link_to 'Back', campanas_path %>

app/views/campanas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campanas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre camapana</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campanas.each do |campana| %>
      <tr>
        <td><%= campana.nombre_camapana %></td>
        <td><%= campana.descripcion %></td>
        <td><%= link_to 'Show', campana %></td>
        <td><%= link_to 'Edit', edit_campana_path(campana) %></td>
        <td><%= link_to 'Destroy', campana, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campana', new_campana_path %>

app/views/campanas/new.html.erb
<h1>New Campana</h1>

<%= render 'form', campana: @campana %>

<%= link_to 'Back', campanas_path %>

app/views/campanas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre camapana:</strong>
  <%= @campana.nombre_camapana %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @campana.descripcion %>
</p>

<%= link_to 'Edit', edit_campana_path(@campana) %> |
<%= link_to 'Back', campanas_path %>